[workspace]
members = ["./codespan", "./codespan-reporting", "./codespan-lsp"]
resolver = "2"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
